apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.8.3
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: nginx-ingress-controller
  createNamespace: true
