apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus
      version: 25.8.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: prometheus
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: 'true'
        hosts:
          - prometheus.domain.com
    alertmanager:
      ingress:
        enabled: true
        className: "nginx"
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - alerts.domain.com
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ['severity', 'namespace']
          group_wait: 1m
          group_interval: 5m
          repeat_interval: 10m
          routes:
          - receiver: 'discord'
            matchers:
            - severity =~ "critical|warning"
            - alertname !~ "KubeProxyDown|KubeSchedulerDown|KubeControllerManagerDown|TargetDown"
            continue: true
        receivers:
          - name: 'discord'
            discord_configs:
              - webhook_url: https://discord.com/api/webhooks/1182345317807562863/nHDbSCzw6F9wJLmoKuBhwqarf2Il9KhGOK1PoxZ52RgpuvPxB3nZG3QPK7KQv1y2NOI6
                send_resolved: true
                title: '{{ template "discord.default.title" . }}'
                message: '{{ template "discord.default.message" . }}'
        templates:
        - '/etc/alertmanager/config/*.tmpl'
    additionalPrometheusRulesMap:
      customrules:
        groups:
          - name: Discord
            rules:
            - alert: TestDiscordAlert
              expr: node_memory_MemAvailable_bytes{instance="10.10.0.4:9100"} < 7000000000
              for: 1m
              labels:
                severity: 'warning'
              annotations:
                summary: "Memory utilization of {{ $labels.instance }} is exceeded 16%"
                description: "Memory utilization of {{ $labels.instance }} Value = {{ $value }}"