apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: prometheus-loki-datasource-sidecar
  labels:
    grafana_datasource: "1"
data:
  prom-loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        editable: false
        url: http://loki-gateway.monitoring.svc.cluster.local
        access: proxy
        isDefault: false
    