apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: prometheus-sidecar-configmap
  labels:
    grafana_datasource: "1"
data:
  prom-loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        editable: false
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: false
    